Review module
matthewb2022/ManySnorkel pull request #10
Opened 2021-07-14 21:35 UTC by matthewb2022

2021-07-14 23:49 UTC, mjmayank1 requested changes
looks good to me, just the one change about rating average

2021-07-14 23:49 UTC, mjmayank1 commented on src/components/BeachPage/BeachPage.js
> +                            initialRating={props.beach.ratings.average}
let's undo this for now

2021-07-15 04:06 UTC, matthewb2022 commented
Fixed based on comment

2021-07-15 04:23 UTC, mjmayank1 commented
it also looks like theres a merge conflict in server.js that you need to fix before this can be merged

2021-07-15 04:56 UTC, mjmayank1 approved these changes

2021-07-15 16:00 UTC, merged